apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: site-management-pod-disruption-budget
  labels:
    name: site-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: site-management
