DELETE FROM site where country_code ='IT' AND popular = true AND id =  23137d6a-f528-4ed7-8a34-53a470d19341;
DELETE FROM site where country_code ='IT' AND popular = true AND id =  442d9a21-58df-48b8-9b78-ae7140e27b55;
DELETE FROM site where country_code ='IT' AND popular = true AND id =  6ed38773-34a6-4694-8e49-a50974f52510;
DELETE FROM site where country_code ='IT' AND popular = true AND id =  6f572529-ad42-4392-a3ad-fc256a8836d9;
DELETE FROM site where country_code ='IT' AND popular = true AND id =  e278a008-bf45-4d19-bb5d-b36ff755be58;
DELETE FROM site where country_code ='IT' AND popular = true AND id =  ecfc4d06-006e-4947-b036-aa4f2d75f067;
