INSERT INTO site_v2 (id, external_id, grouping_by, login_type, name, provider, account_type_whitelist)
VALUES (162b5f67-b83c-4dd7-84b3-31040075fe5b, '15521', NULL, NULL, 'Vanquis Bank (UK)', 'YODLEE', ['CURRENT_ACCOUNT', 'SAVINGS_ACCOUNT', 'CREDIT_CARD']);

INSERT INTO popular_country_site_ranking (site_id, country_code, ranking, popular)
VALUES (162b5f67-b83c-4dd7-84b3-31040075fe5b, 'GB', NULL, false);