DELETE FROM popular_country_site_ranking where site_id= 37b9aef8-04d1-4513-ba61-be367e578664;
DELETE FROM popular_country_site_ranking where site_id= 51699d57-68e5-4db3-9a64-9ae33f518de3;
INSERT INTO popular_country_site_ranking (site_id, country_code, popular, ranking) VALUES (37b9aef8-04d1-4513-ba61-be367e578664, 'GB', false, NULL);
INSERT INTO popular_country_site_ranking (site_id, country_code, popular, ranking)VALUES (51699d57-68e5-4db3-9a64-9ae33f518de3, 'GB', false, NULL);
