UPDATE site_v2 SET name = 'Widiba' WHERE id = ce55750b-cab1-4c12-abd2-5b79a2015127;
UPDATE site_v2 SET name = 'Banco BPM' WHERE id = 4c0d5639-20ca-493b-847f-a8030eee0450;
UPDATE site_v2 SET name = 'Cassa di Risparmio Bologna' WHERE id = 975d54db-a56a-4faa-9661-c64c09f5b4fc;
UPDATE site_v2 SET name = 'Cassa di Risparmio del Friuli Venezia Giulia' WHERE id = d71d9c74-b3e4-4fff-8c69-a501f9d443db;
UPDATE site_v2 SET name = 'Cassa di Risparmio di Firenze' WHERE id = 3e8d3311-3d2e-43f9-a5eb-108bd942bfe7;
UPDATE site_v2 SET name = 'Casse di Risparmio dell’Umbria' WHERE id = 6be57e2c-0fba-4550-9390-7acad3766d80;
UPDATE site_v2 SET name = 'Cassa di Risparmio di Pistoia e della Lucchesia' WHERE id = 91a07f33-abbf-408a-ad57-de04171ef19f;
UPDATE site_v2 SET name = 'ING' WHERE id = 5300500b-6b83-4fdc-a8bc-7c2f9be014d4;