UPDATE site_v2 SET available_in_countries = ['GB', 'IT', 'NL', 'FR'] where id = 3673486a-2ff0-4508-8de1-b8b1fbf213f4;
INSERT INTO popular_country_site_ranking (site_id, country_code, popular, ranking) VALUES (3673486a-2ff0-4508-8de1-b8b1fbf213f4, 'IT', true, NULL);
INSERT INTO popular_country_site_ranking (site_id, country_code, popular, ranking) VALUES (3673486a-2ff0-4508-8de1-b8b1fbf213f4, 'NL', true, NULL);
INSERT INTO popular_country_site_ranking (site_id, country_code, popular, ranking) VALUES (3673486a-2ff0-4508-8de1-b8b1fbf213f4, 'FR', true, NULL);