UPDATE site_v2 SET grouping_by = 'ING Italia' WHERE id = 5300500b-6b83-4fdc-a8bc-7c2f9be014d4;
UPDATE site_v2 SET name = 'ING Italia' WHERE id = d7bb748d-c94a-4a17-9a63-6c280f2654f2;
UPDATE site_v2 SET name = 'ING Italia' WHERE id = f6880396-7b95-4c37-969e-331c3450c7d6;
UPDATE site_v2 SET grouping_by = 'ING Italia' WHERE id = d7bb748d-c94a-4a17-9a63-6c280f2654f2;
UPDATE site_v2 SET grouping_by = 'ING Italia' WHERE id = f6880396-7b95-4c37-969e-331c3450c7d6;

UPDATE popular_country_site_ranking SET popular = true WHERE site_id = d7bb748d-c94a-4a17-9a63-6c280f2654f2 AND country_code = 'IT';
UPDATE popular_country_site_ranking SET popular = true WHERE site_id = f6880396-7b95-4c37-969e-331c3450c7d6 AND country_code = 'IT';