UPDATE site_v2 SET account_type_whitelist = ['CURRENT_ACCOUNT','SAVINGS_ACCOUNT','CREDIT_CARD'] WHERE id = 8e96ad29-fd1c-40cb-b28f-826b022f2763;
UPDATE site_v2 SET account_type_whitelist = ['CURRENT_ACCOUNT','SAVINGS_ACCOUNT','CREDIT_CARD'] WHERE id = 8b21aab6-e0a3-43ae-be5e-def71509bef0;
UPDATE site_v2 SET account_type_whitelist = ['CURRENT_ACCOUNT','SAVINGS_ACCOUNT','CREDIT_CARD'] WHERE id = fdf5c571-7025-4569-b240-2be87b22f9aa;
UPDATE site_v2 SET account_type_whitelist = ['CURRENT_ACCOUNT','SAVINGS_ACCOUNT','CREDIT_CARD'] WHERE id = dda2651f-9518-409b-9b5e-6e0d1ccd0112;