insert into popular_country_site_ranking (site_id, country_code, popular, ranking)
values (33aca8b9-281a-4259-8492-1b37706af6db, 'NL', True, 0);
insert into popular_country_site_ranking (site_id, country_code, popular, ranking)
values (33aca8b9-281a-4259-8492-1b37706af6db, 'CZ', True, 0);
insert into popular_country_site_ranking (site_id, country_code, popular, ranking)
values (33aca8b9-281a-4259-8492-1b37706af6db, 'PL', True, 0);
