delete from popular_country_site_ranking where site_id = 032b3544-925b-4b92-b84d-23e45d16a704 and country_code = 'GB';
delete from popular_country_site_ranking where site_id = 650d5187-6beb-4411-b107-69cea2891759 and country_code = 'GB';
delete from popular_country_site_ranking where site_id = 26c67b2b-91d3-491f-8121-b02fc9420101 and country_code = 'GB';
delete from popular_country_site_ranking where site_id = 9811a3bd-1c8d-4461-b795-4ff63868fc58 and country_code = 'GB';
delete from popular_country_site_ranking where site_id = 49665f18-2cc6-4b0a-bd66-c8037dda7058 and country_code = 'GB';
delete from popular_country_site_ranking where site_id = bb5c3c49-f6c2-45c2-9067-855df78e6864 and country_code = 'GB';
