apiVersion: v1
kind: Service
metadata:
  name: site-management
  labels:
    team: yts-core
spec:
  selector:
    name: site-management
    serving: "true"
  ports:
    - port: 443
      name: https
      targetPort: 8443
